lagoon_id: "costa_del_lago"
source: rockwell
poll_seconds: 1

timezone: "America/Asuncion" 


backend:
  url: "http://localhost:8000/ingest/scada"

rockwell:
  ip: "192.168.11.10"
  slot: 0

tags:
  PT117_R_SCADA: "PT117_R_SCADA"
  PT148_R_SCADA: "PT148_R_SCADA"
  PT141_R_SCADA: "PT141_R_SCADA"
  PT143_R_SCADA: "PT143_R_SCADA"
  PT145_R_SCADA: "PT145_R_SCADA"
  WM01_TOT_SCADA: "WM01_TOT_SCADA"
  DIF_PRES_SCADA: "DIF_PRES_SCADA"
  P002_STS_SCADA: "P002_STS_SCADA"
  P006_STS_SCADA: "P006_STS_SCADA"
  P007_STS_SCADA: "P007_STS_SCADA"
  RETRO_SCADA: "RETRO_SCADA"

