lagoon_id: "aquavista"
source: siemens
poll_seconds: 1

force_reconnect_every_sec: 3600
max_consecutive_fails: 10

backend:
  url: "http://localhost:8000/ingest/scada"


timezone: "America/Mexico_City" 

siemens:
  opc_server_url: "opc.tcp://192.168.17.10:4840"
  timeout_sec: 1
  # opcional
  # username: "user"
  # password: "pass"

# keys l√≥gicas 
tags:
  Tags_01_Real: "ns=4;i=3"
  Tags_02_Real: "ns=4;i=4"
  Tags_03_Real: "ns=4;i=5"
  Tags_04_Real: "ns=4;i=18"